// utils/mappers.ts
export function profileApiToForm(data: any) {
  return {
    id: data.id,
    firstName: data.first_name,
    middleName: data.middle_name,
    lastName: data.last_name,
    address: data.address,
    secondaryAddress: data.secondary_address,
    city: data.city,
    state: data.state,
    country: data.country,
    zipCode: data.zip_code,
    phone: data.phone,
    certificateNumber: data.certificate_number,
    birth: data.birth,
    DOBShort: data.DOB_short,
    birthPlace: data.birth_place,
    nacionality: data.nacionality,
    gender: data.gender,
    clan: data.clan,
    height: data.height,
    weight: data.weight,
    eyeColor: data.eye_color,
    hairColor: data.hair_color,
    sign: data.sign,
    fingerprints: data.fingerprints,
    photo: data.photo,
    email: data.email,
    role: data.role,
    password: '' // opcional, depende cómo lo manejes
  }
}

export function profileFormToApi(data: any) {
  return {
    id: data.id,
    first_name: data.firstName,
    middle_name: data.middleName,
    last_name: data.lastName,
    address: data.address,
    secondary_address: data.secondaryAddress,
    city: data.city,
    state: data.state,
    country: data.country,
    zip_code: data.zipCode,
    phone: data.phone,
    certificate_number: data.certificateNumber,
    birth: data.birth,
    DOB_short: data.DOBShort,
    birth_place: data.birthPlace,
    nacionality: data.nacionality,
    gender: data.gender,
    clan: data.clan,
    height: data.height,
    weight: data.weight,
    eye_color: data.eyeColor,
    hair_color: data.hairColor,
    sign: data.sign,
    fingerprints: data.fingerprints,
    photo: data.photo,
    email: data.email,
    role: data.role,
    password: data.password
  }
}
